//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaboFrowardMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPRESAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPRESAS()
        {
            this.SOLICITUDES = new HashSet<SOLICITUDES>();
            this.VEHICULOS = new HashSet<VEHICULOS>();
        }
    
        public int ID_EMPRESA { get; set; }
        public int ID_TIPO_EMPRESA { get; set; }
        public int RUT { get; set; }
        public string DV { get; set; }
        public string NOMBRES { get; set; }
        public string GIRO { get; set; }
        public bool INACTIVO { get; set; }
    
        public virtual TIPOS_EMPRESAS TIPOS_EMPRESAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOLICITUDES> SOLICITUDES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEHICULOS> VEHICULOS { get; set; }
    }
}
