//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaboFrowardMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCACIONES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOCACIONES()
        {
            this.PERF_US_ADMIN_LOC = new HashSet<PERF_US_ADMIN_LOC>();
        }
    
        public int ID_LOCACION { get; set; }
        public string ES_INFORMADA { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<int> ID_PUERTO { get; set; }
        public Nullable<bool> INACTIVO { get; set; }
    
        public virtual PUERTOS PUERTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERF_US_ADMIN_LOC> PERF_US_ADMIN_LOC { get; set; }
    }
}
