//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaboFrowardMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIMIENTOS_HISTORICOS
    {
        public int ID_MOVIMIENTO { get; set; }
        public Nullable<int> ID_VEHICULO { get; set; }
        public Nullable<int> MOV_ID_MOVIMIENTO { get; set; }
        public Nullable<int> ID_DISPOSITIVO { get; set; }
        public Nullable<long> ID_PERSONA_APROBADA { get; set; }
        public System.DateTime FECHA { get; set; }
        public string COBRAR { get; set; }
    
        public virtual DISPOSITIVOS DISPOSITIVOS { get; set; }
        public virtual MOVIMIENTOS MOVIMIENTOS { get; set; }
        public virtual PERSONAS_APROBADAS PERSONAS_APROBADAS { get; set; }
        public virtual VEHICULOS VEHICULOS { get; set; }
    }
}
