//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaboFrowardMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NAVES_PROGRAMADAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NAVES_PROGRAMADAS()
        {
            this.PERSONAS_APROBADAS = new HashSet<PERSONAS_APROBADAS>();
        }
    
        public long ID_NAVES_PROGRAMADAS { get; set; }
        public int ID_NAVE { get; set; }
        public System.DateTime FECHA_ARRIBO { get; set; }
        public System.DateTime FECHA_ZARPE { get; set; }
    
        public virtual NAVES NAVES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERSONAS_APROBADAS> PERSONAS_APROBADAS { get; set; }
    }
}
