//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaboFrowardMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERF_US_ADMIN_LOC
    {
        public int ID_LOCACION { get; set; }
        public int ID_USUARIO { get; set; }
    
        public virtual LOCACIONES LOCACIONES { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
        public virtual PERF_US_ADMIN_LOC PERF_US_ADMIN_LOC1 { get; set; }
        public virtual PERF_US_ADMIN_LOC PERF_US_ADMIN_LOC2 { get; set; }
    }
}
