//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaboFrowardMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONAS_EN_SOLICITUDES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERSONAS_EN_SOLICITUDES()
        {
            this.PERSONAS_APROBADAS = new HashSet<PERSONAS_APROBADAS>();
        }
    
        public long ID_PERSONA_SOLICITUD { get; set; }
        public Nullable<int> ID_NAVE { get; set; }
        public int ID_PERSONA { get; set; }
        public Nullable<int> ID_LOCACION { get; set; }
        public long ID_SOLICITUD { get; set; }
    
        public virtual NAVES NAVES { get; set; }
        public virtual PERSONAS PERSONAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERSONAS_APROBADAS> PERSONAS_APROBADAS { get; set; }
        public virtual SOLICITUDES SOLICITUDES { get; set; }
    }
}
