//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaboFrowardMVC.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class PERSONAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERSONAS()
        {
            this.PERSONAS_EN_SOLICITUDES = new HashSet<PERSONAS_EN_SOLICITUDES>();
            this.USUARIOS = new HashSet<USUARIOS>();
        }
    
        public int ID_PERSONA { get; set; }
        public Nullable<int> ID_NACIONALIDAD { get; set; }
        public int RUT { get; set; }
        public string DV { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDOMATERNO { get; set; }
        public string APELLIDOPATERNO { get; set; }
        public bool INACTIVO { get; set; }
        public string PASAPORTE { get; set; }
		[System.ComponentModel.DataAnnotations.DataType(DataType.Date)]
		[DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
		public Nullable<System.DateTime> FECHAINDUCCION { get; set; }
    
        public virtual NACIONALIDADES NACIONALIDADES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERSONAS_EN_SOLICITUDES> PERSONAS_EN_SOLICITUDES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIOS> USUARIOS { get; set; }
    }
}
