//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaboFrowardMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONAS_APROBADAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERSONAS_APROBADAS()
        {
            this.MOVIMIENTOS_HISTORICOS = new HashSet<MOVIMIENTOS_HISTORICOS>();
        }
    
        public long ID_PERSONA_APROBADA { get; set; }
        public int ID_USUARIO { get; set; }
        public Nullable<long> ID_PERSONA_SOLICITUD { get; set; }
        public System.DateTime FECHA_APROBACION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOVIMIENTOS_HISTORICOS> MOVIMIENTOS_HISTORICOS { get; set; }
        public virtual PERSONAS_EN_SOLICITUDES PERSONAS_EN_SOLICITUDES { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
        public virtual NAVES_PROGRAMADAS NAVES_PROGRAMADAS { get; set; }
    }
}
