//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaboFrowardMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUDES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SOLICITUDES()
        {
            this.PERSONAS_EN_SOLICITUDES = new HashSet<PERSONAS_EN_SOLICITUDES>();
            this.VEHICULOS = new HashSet<VEHICULOS>();
        }
    
        public long ID_SOLICITUD { get; set; }
        public int ID_TIPO_INGRESO { get; set; }
        public int ID_PUERTO { get; set; }
        public int ID_USUARIO { get; set; }
        public int ID_EMPRESA { get; set; }
        public System.DateTime FECHA_SOLICITUD { get; set; }
        public System.DateTime FECHA_DESDE { get; set; }
        public System.DateTime FECHA_HASTA { get; set; }
    
        public virtual EMPRESAS EMPRESAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERSONAS_EN_SOLICITUDES> PERSONAS_EN_SOLICITUDES { get; set; }
        public virtual PUERTOS PUERTOS { get; set; }
        public virtual TIPOS_INGRESOS TIPOS_INGRESOS { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEHICULOS> VEHICULOS { get; set; }
    }
}
