//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaboFrowardMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIOS()
        {
            this.PERF_US_ADMIN_LOC = new HashSet<PERF_US_ADMIN_LOC>();
            this.PERSONAS_APROBADAS = new HashSet<PERSONAS_APROBADAS>();
            this.SOLICITUDES = new HashSet<SOLICITUDES>();
            this.PERFILES = new HashSet<PERFILES>();
        }
    
        public int ID_USUARIO { get; set; }
        public string NOMBRE { get; set; }
        public string PASSWORD { get; set; }
        public string TELEFONO { get; set; }
        public Nullable<bool> INACTIVO { get; set; }
        public Nullable<bool> aprueba_nave { get; set; }
        public Nullable<int> ID_PERSONA { get; set; }
        public string CLAVE_INICIAL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERF_US_ADMIN_LOC> PERF_US_ADMIN_LOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERSONAS_APROBADAS> PERSONAS_APROBADAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOLICITUDES> SOLICITUDES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERFILES> PERFILES { get; set; }
        public virtual PERSONAS PERSONAS { get; set; }
    }
}
